# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provision "shell", inline: "yum update -y"

  config.vm.define "web" do |web|
    web.vm.hostname = "web-server"
    config.vm.provision "shell",
      path: "~/projects/vagrant/scripts/web.sh"
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db-server"
    config.vm.provision "shell",
      path: "~/projects/vagrant/scripts/db.sh"
  end
end
